#!/bin/sh

# Called by "git push" after it has checked the remote status, but before
# anything has been pushed. If this script exits with a non-zero status
# nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
    if [ "$local_oid" = "$zero" ]; then
        # skip deletes
        exit 0
    fi
    if ! git cat-file -e $local_oid:setup.cfg; then
        # if there's no setup.cfg, don't bother checking
        #echo No setup.cfg
        exit 0
    fi
    
    tagversion=$(echo $local_ref | sed -n "s/^refs\/tags\/\(v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\)$/\1/p")
    #echo tagversion=$tagversion
    pkgfile=$(git cat-file blob $local_oid:setup.cfg | sed -n "s/^name *= *\(.*\) *$/\1/p")/__init__.py
    #echo pkgfile=$pkgfile
    
    if ! git cat-file -e $local_oid:"$pkgfile"; then
        # if there's no pkgfile, don't bother checking
        #echo No $pkgfile
        exit 0
    fi
    fileversion=v$(git cat-file blob $local_oid:"$pkgfile" | sed -n "s/^__version__ *= *\"\(.*\)\" *$/\1/p")
    #echo fileversion=$fileversion
    if [ -z "$fileversion" ]; then
        # if there's no fileversion, don't bother checking
        #echo No file version
        exit 0
    fi
    
    if [ -n "$tagversion" ]; then
        # Check if current commit has matching version number
        if [ "$tagversion" != "$fileversion" ]; then
            echo "#"
            echo "# Did you forget to update the version number?"
            echo "#"
            exit 1
        fi
    else
        # Check if version number tag exists
        if [ ! $(git tag -l "$fileversion") ]; then
            echo "#"
            echo "# Did you forget to create a $fileversion tag?"
            echo "#"
            exit 1
        fi
    fi
done

exit 0
